In [95]:
import numpy as np
import numpy.linalg as linalg  # linalg.det() este determinantul unei matrice


In [110]:
a = np.array([
    [1, 0, 1],
    [1, 2, 3],
    [3, 2, 1]
])

print('linalg.det(a):')
print(linalg.det(a))

a_ = linalg.inv(a)
print('Reverse of a:')
print(a_)

print("a @ a_inverse:")
print(a @ a_)

linalg.det(a):
-8.000000000000002
Reverse of a:
[[ 0.5  -0.25  0.25]
 [-1.    0.25  0.25]
 [ 0.5   0.25 -0.25]]
a @ a_inverse:
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 3.33066907e-16  1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  0.00000000e+00  1.00000000e+00]]


In [97]:
# Cum aflam dimensiunea matricea?
b = np.array([
    [1,0,1],
    [1,0,1],
])
print(b.shape)
print(b.shape[0], 'linii', b.shape[1], 'coloane')

(2, 3)
2 linii 3 coloane


In [98]:
# Cum generam matricea unitate si matricea vida

I3 = np.eye(3)
O3 = np.zeros((3, 3))
print(I3)
print(O3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [99]:
# transpusa și înmulțire matrice:

a = np.array([
    [1, 2, 3],
    [1, -2, 3],
    [1, 0, 0],
])
print('a = ')
print(a)  # afisam matricea a
print('a.T = ')
print(a.T)  # transpusa

# produs matricela:
b = a @ a.T
a_copy = a @ I3
print("a @ a.T =")
print(b)
print("a @ I3 =")
print(a_copy)

a = 
[[ 1  2  3]
 [ 1 -2  3]
 [ 1  0  0]]
a.T = 
[[ 1  1  1]
 [ 2 -2  0]
 [ 3  3  0]]
a @ a.T =
[[14  6  1]
 [ 6 14  1]
 [ 1  1  1]]
a @ I3 =
[[ 1.  2.  3.]
 [ 1. -2.  3.]
 [ 1.  0.  0.]]


In [100]:
# cum cream subvectori:
v = np.array([2, 3, 4, 5, -2, 100, 101])

print('v =')
print(v)
# cate un element:
print('v[0] v[3]')
print(v[0], v[3])
# cate un slice (in acest caz mai este numit range:
print(v[3:5])  # valorile de pe indicii 3,4 pana inainte de 5, deoarece 5=STOP
# cate un slice, dar din k in k elemente
print(v[0:7:3])  # indici 1,2,3,4,5,6 dar luați din 7 in 7

v =
[  2   3   4   5  -2 100 101]
v[0] v[3]
2 5
[ 5 -2]
[  2   5 101]


In [101]:
# cum cream submatrice
a = np.array([
    [6, 2, -5],
    [0, -2, 7],
    [6, 0, 2],
])

# matricea a:
print('a =')
print(a)

# Putem folosi indici pentru a lua un element:
print('a[1, 2] = a[1][2] =')
print(a[1, 2])  # a_{12}

# putem folosi slices pentru ambele coordonate:

# linia 1
print(a[1])
# coloana 2:
print(a[:, 2])



a =
[[ 6  2 -5]
 [ 0 -2  7]
 [ 6  0  2]]
a[1, 2] = a[1][2] =
7
[ 0 -2  7]
[-5  7  2]


In [102]:
# matricea a:
print('a =')
print(a)

# liniile 1 și 2
print(a[1:3, :])
# coloanele 0 și 2
print(a[:, 0:3:2])

a =
[[ 6  2 -5]
 [ 0 -2  7]
 [ 6  0  2]]
[[ 0 -2  7]
 [ 6  0  2]]
[[ 6 -5]
 [ 0  7]
 [ 6  2]]


In [103]:
# matricea a:
print('a =')
print(a)

# liniile 0 si 1, coloanele 1 si 2
print("a[0:2, 1:3] =")
print(a[0:2, 1:3])

a =
[[ 6  2 -5]
 [ 0 -2  7]
 [ 6  0  2]]
a[0:2, 1:3] =
[[ 2 -5]
 [-2  7]]


In [104]:
# TODO
a = np.array([
    [-5, 2, 10],
    [-2, -3, 4],
    [-5, 8, 102],
    [0, 3, 10],
])

# Cerinta:
# Extrageți si afișați, pe rand, fiecare dintre următoarele:

# 1. Coloana care conține cele mai multe elemente negative


# 2. Linia  care conține cele mai multe elemente negative


# 3. Extrageți din matricea de mai sus orice matrice de 2x2, care conține doar elemente pare


# 4. Extrageți o matrice de 2x2 care conține număr maxim de elemente negative


# 5. E



In [105]:
from numpy.typing import NDArray

# 1. distanta dintre doua puncte

# 2D
a = np.array([2, 3])
b = np.array([5, 1])

# 3D
m = np.array([0,0,0])
n = np.array([0,2,3])

# creăm funcții
def distanta_euclidiana(a: NDArray, b: NDArray) -> float:
    pass

dist = distanta_euclidiana(a, b)
print(dist == np.sqrt(13))

False
